@startuml
skinparam classAttributeIconSize 0

package violence{
    class ViolenceCard
    class ViolenceCardManadgement
    package enums {
        enum Types{
            PHYSICAL
            ECONOMIC
            VERBAL
            PSYCHOLOGICAL
            SEXUAL
        }
        enum Backgrounds{
            ..Fields..
            - image : Images
        }
        enum Icon{
            ..Fields..
            - image : Images
        }
        enum Acts
    }
}
violence.ViolenceCard *-->"1\n-_icon" violence.enums.Icon
violence.ViolenceCard *-->"1\n-_background" violence.enums.Backgrounds
violence.ViolenceCard *-->"1\n-_acts" violence.enums.Acts
violence.ViolenceCardManadgement ..> violence.ViolenceCard : uses
violence.ViolenceCardManadgement ..> violence.enums.Types : uses
@enduml