@startuml
skinparam classAttributeIconSize 0

package violence{
    class ViolenceCard
    class ViolenceCardManager
    package enums {
        enum Types{
            PHYSICAL
            ECONOMIC
            VERBAL
            PSYCHOLOGICAL
            SEXUAL
        }
        enum Backgrounds{
            ..Fields..
            - type : Types
            - image : Images
            ..Methods..
            <<create>> Backgrounds(type : Types, background : Images)
        }
        enum Icon{
            ..Fields..
            - type : Types
            - image : Images
            ..Methods..
            <<create>> Icon(type : Types, icon : Images)
        }
        enum Acts{
        ..Fields..
        - type : Types
        - description : String
        ..Methods..
        <<create>> Acts(type : Types, description : String)
        }
    }
}
violence.ViolenceCard *-->"1\n-_icon" violence.enums.Icon
violence.ViolenceCard *-->"1\n-_background" violence.enums.Backgrounds
violence.ViolenceCard *-->"1\n-_acts" violence.enums.Acts
violence.ViolenceCardManager ..> violence.ViolenceCard : uses
violence.ViolenceCardManager ..> violence.enums.Types : uses
@enduml